# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poke',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
