# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0002_user_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poke',
        ),
    ]
