# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0004_poke'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pokes', to='login3_app.User'),
            preserve_default=False,
        ),
    ]
