# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0005_poke_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='updated_at',
        ),
    ]
