# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0006_auto_20170628_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='pokes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
