# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0007_auto_20170628_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='login3_app.User')),
            ],
        ),
    ]
