# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0008_poker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='poker',
            name='last_name',
        ),
    ]
