# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0010_poker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poker',
            name='name',
        ),
    ]
