# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0012_poker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='poker',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pokes',
        ),
        migrations.DeleteModel(
            name='Poker',
        ),
        migrations.AddField(
            model_name='poke',
            name='pokee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='login3_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='login3_app.User'),
        ),
    ]
