# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login3_app', '0014_auto_20170629_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='pokes',
            field=models.IntegerField(default=0),
        ),
    ]
